[project]
name = "sqlite-mvs"
version = "0.1.0-dev"
type = "library"

[build]
cflags = [
  "-std=gnu89",
  "-O0",
  "-I", "vendor/sqlite",
  "-include", "include/sqlite3_mvs_compat.h",
  "-include", "include/sqlite3_mvs_names.h",
]

[[module]]
name = "SQLTTEST"
entry = "@@CRT0"
startup = "crt1"
sources = [
  "vendor/sqlite/sqlite3.c",
  "src/sqlite3_mvs.c",
  "tests/core_link.c",
]

[[module]]
name = "SQLITSO"
entry = "@@CRT0"
startup = "crt0"
sources = [
  "vendor/sqlite/sqlite3.c",
  "src/sqlite3_mvs.c",
  "src/sqlite_tso.c",
  "asm/tsqtget.asm",
  "asm/tsqtput.asm",
]

[[module]]
name = "SQLITEA"
entry = "@@CRT0"
startup = "crt1"
sources = [
  "vendor/sqlite/sqlite3.c",
  "src/sqlite3_mvs.c",
  "src/sqlite_cobol_start.c",
  "src/sqlite_cobol_api.c",
]

[[module]]
name = "SQLITEX"
entry = "@@CRT0"
startup = "crt1"
sources = [
  "vendor/sqlite/sqlite3.c",
  "src/sqlite3_mvs.c",
  "src/sqlite_cobol_x_start.c",
  "src/sqlite_cobol_x_api.c",
]

[deploy]
target = "IBMUSER.SQLITE.LOAD"

[artifacts]
loads = true
