[project]
name = "sqlite-mvs-353-candidate"
version = "3.53.4"
type = "application"

[[module]]
name = "SQLT534"
entry = "@@CRT0"
startup = "crt1"
sources = []

[[module]]
name = "SQLI534"
entry = "@@CRT0"
startup = "crt0"
sources = []

[[module]]
name = "SQLITEA"
entry = "@@CRT0"
startup = "crt1"
sources = []

[[module]]
name = "SQLITEX"
entry = "@@CRT0"
startup = "crt1"
sources = []

[[module]]
name = "SQLIMPRT"
entry = "@@CRT0"
startup = "crt1"
sources = []

[deploy]
target = "IBMUSER.SQLITE.D534.LOAD"

[artifacts]
loads = true
