#ifndef SQLITE_COBOL_X_H
#define SQLITE_COBOL_X_H

#define SQLX_MAX_SQL 2048
#define SQLX_MAX_BINDS 8
#define SQLX_MAX_COLUMNS 16
#define SQLX_MAX_ROWS 10
#define SQLX_VALUE_SIZE 64
#define SQLX_BIND_SIZE 68
#define SQLX_CELL_SIZE 68
#define SQLITE_COBOL_RC_BAD_ARGUMENT 100

#define SQLX_OFF_OPERATION 0
#define SQLX_OFF_SQL_LENGTH 8
#define SQLX_OFF_SQL 10
#define SQLX_OFF_BIND_COUNT 2058
#define SQLX_OFF_BINDS 2060
#define SQLX_OFF_MAX_ROWS 2604
#define SQLX_OFF_ROW_COUNT 2606
#define SQLX_OFF_COLUMN_COUNT 2608
#define SQLX_OFF_CHANGES 2610
#define SQLX_OFF_RETURN_CODE 2612
#define SQLX_OFF_MESSAGE_LENGTH 2614
#define SQLX_OFF_MESSAGE 2616
#define SQLX_OFF_COLUMN_NAMES 2776
#define SQLX_OFF_CELLS 3288
#define SQLX_REQUEST_SIZE 14168

void sqlite_cobol_x_entry(unsigned char *request);

#endif
