#!/usr/bin/env python3
"""Generate stable 8-character MVS aliases for SQLite public API symbols."""

from pathlib import Path
import re
import argparse


ROOT = Path(__file__).resolve().parents[1]
DEFAULT_HEADER = ROOT / "vendor/sqlite/sqlite3.h"
DEFAULT_OUTPUT = ROOT / "include/sqlite3_mvs_names.h"


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--header", type=Path, default=DEFAULT_HEADER)
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    args = parser.parse_args()
    header = args.header.resolve()
    output = args.output.resolve()
    text = header.read_text(encoding="utf-8")
    statements = re.findall(r"\bSQLITE_API\b.*?;", text, flags=re.DOTALL)
    names = {"sqlite3_os_init", "sqlite3_os_end"}
    for statement in statements:
        declared = re.findall(
            r"\b(sqlite3_[A-Za-z0-9_]+)\s*(?=\(|\[)", statement
        )
        if declared:
            names.update(declared)
        else:
            tokens = re.findall(r"\bsqlite3_[A-Za-z0-9_]+\b", statement)
            if tokens:
                names.add(tokens[-1])

    # A SQLITE_THREADSAFE=0 amalgamation replaces this family with internal
    # macros after the forced-include header has been read.
    names = {name for name in names if not name.startswith("sqlite3_mutex_")}

    lines = [
        "/* Generated by tools/gen_mvs_names.py; do not edit. */",
        "#ifndef SQLITE3_MVS_NAMES_H",
        "#define SQLITE3_MVS_NAMES_H",
        "",
    ]
    for number, name in enumerate(sorted(names), start=1):
        lines.append(f"#define {name} SQ{number:06d}")
    lines.extend(["", "#endif", ""])
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text("\n".join(lines), encoding="ascii")
    try:
        shown = output.relative_to(ROOT)
    except ValueError:
        shown = output
    print(f"generated {shown} with {len(names)} aliases")


if __name__ == "__main__":
    main()
